//created on: Feb 16, 2013
package Particle

import com.meleemistress.core.Particle;
import com.meleemistress.core.ParticleEngine;

//list any import classes here.



//declare any global variables here



//initialization: set position, velocity

rule "initialize the particle"
    when 
        p : Particle(xvel == 0 && yvel == 0)
    then
        System.out.println("init");
        p.generateStartingPositionAndVelocity();
end



//movement: update position

rule "update particle position"
    when
        p : Particle(x != null)
    then
        System.out.println("update");
        p.updatePosition();
end


/*rule "When a particle is found, print its name"

    when
        $p : Particle()
    then
        System.out.println($p.getName() + ": pennies " + $p.getPennies() + " luck: " + $p.getLuck());
        //calling update in a rule causes the rules to be reevaluated. This messes with the
        //concept of state iterations
        $p.lookForAPenny();
    
        $p.setX($p.getX() + 5);
        
end */


