//created on: Feb 16, 2013
package Particle

import com.meleemistress.core.Particle;
import com.meleemistress.core.MovingParticle;
import com.meleemistress.core.ParticleEngine;




//declare any global variables here



//initialization: set position, velocity
rule "initialize the particle"
    when 
        p : MovingParticle(xvel == 0 && yvel == 0)
    then
        p.generateStartingPositionAndVelocity();
end



//movement: update position

rule "bounce off a side wall"
    salience 1  //execute this before updating position
    when
        p : MovingParticle(x == ParticleEngine.DIMENSION || x == 0)
    then
        //if we've hit the boundary of the viewing window, invert the x velocity
        p.setXvel(-p.getXvel());
end

rule "bounce off the floor or ceiling"
    salience 1 //execute this before updating position
    when
        p : MovingParticle(y == ParticleEngine.DIMENSION || y == 0)
    then
        //if we've hit the boundary of the window, invert the y velocity
        p.setYvel(-p.getYvel());
end

rule "update particle position"
    when
        //all positions get updated, all the time
        p : MovingParticle()
    then
        p.updatePosition();
end




